"""criado tabelas

Revision ID: 1b7baa4d10e0
Revises: 
Create Date: 2024-07-06 00:31:31.223386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7baa4d10e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('categoryId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoryName', sa.String(length=80), nullable=True),
    sa.Column('categoryDesc', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('categoryId')
    )
    op.create_table('products_data',
    sa.Column('productId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('productName', sa.String(length=100), nullable=True),
    sa.Column('productImageUrl', sa.String(length=100), nullable=True),
    sa.Column('productPrice', sa.Numeric(), nullable=True),
    sa.Column('productDesc', sa.String(length=500), nullable=True),
    sa.Column('productCategory', sa.String(length=40), nullable=True),
    sa.Column('productAmount', sa.Numeric(), nullable=True),
    sa.Column('productAmountSuggestion', sa.Numeric(), nullable=True),
    sa.Column('vendorName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('productId')
    )
    op.create_table('sold_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clientName', sa.String(length=100), nullable=False),
    sa.Column('vendorName', sa.String(length=100), nullable=False),
    sa.Column('productId', sa.Integer(), nullable=True),
    sa.Column('productName', sa.String(length=100), nullable=True),
    sa.Column('productCategory', sa.String(length=40), nullable=True),
    sa.Column('soldAmount', sa.Numeric(), nullable=True),
    sa.Column('soldTime', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username', name='unique_username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('sold_products')
    op.drop_table('products_data')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
